# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
              name:
                  description: 'Person to greet'
                  required: true
                  default: 'Mona the Octocat'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Build application with Maven
        run: mvn -B -Djib.console=plain -f ./eureka-server/pom.xml compile jib:build
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
